#!/bin/bash

# Script for downloading files from Yandex.Disk
# Скрипт для загрузки файлов с Яндекс.Диска
# 09.06.2019, GPLv3+

YA_LINK="$1"
PAGE="`mktemp yadisk-XXXXXXX`"
COOKIE="`mktemp yacookie-XXXXXXX`"
AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"

# Get main page with JSON stuff inside
wget --quiet --no-check-certificate -O ${PAGE} --keep-session-cookies\
  --save-cookies=${COOKIE} -U "${AGENT}" ${YA_LINK} #2> /dev/null

# Retrieve required parameters from JSON
YA_HASH="`cat ${PAGE} | sed 's/,/\n/g' | grep \\"hash\\": | tail -n1 | cut -d'"' -f4`"
YA_SKEY="`cat ${PAGE} | grep \\\"sk\\\" | sed 's/,"/,\n"/g' | grep \\\"sk\\\" | cut -d '"' -f4`"
YA_NAME="`cat ${PAGE} | sed 's/,/\n/g' | grep ^\\"name\\": | grep -v script | \
  cut -d'"' -f4`"

echo SKEY ${YA_SKEY}
echo HASH ${YA_HASH}
echo NAME ${YA_NAME}

# Don't need page anymore
rm ${PAGE}

# Range header (Curl does this automatically, so it's commented out)
#if [ -f ${YA_NAME} ]; then
#  RANGE="--header='Range: bytes=`ls -l ${YA_NAME} | cut -d' ' -f5`-'";
#  echo ${RANGE}
#fi

# Create POST data for Yandex.Disk API request
PAYLOAD=`echo -ne "{\"hash\":\"${YA_HASH}\",\"sk\":\"${YA_SKEY}\"}" | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g'`
#echo "Payload is ${PAYLOAD}"

# Make the API request and get URL from the response
URL="`curl -s\
      -A "${AGENT}" \
      -b ${COOKIE} \
      --data-raw ${PAYLOAD} \
      -e ${YA_LINK} \
      -H "origin: https://yadi.sk" \
      -H "content-type: text/plain" \
      'https://yadi.sk/public/api/download-url' \
      | sed 's/"/\n/g' | grep https`"

echo URL ${URL}

# At last, download the file
echo "Downloading..."
echo ${URL} | xargs curl -L -C - -A "${AGENT}" -b ${COOKIE} -o "${YA_NAME}" 

# Cleanup cookies
rm ${COOKIE}
